train:
  _target_: src.datasets.LibrispeechDataset
  # part: "train-clean-100"
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
