train:
  _target_: src.datasets.LibrispeechDataset
  part: "train_all"
  instance_transforms: ${transforms.instance_transforms.train}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  instance_transforms: ${transforms.instance_transforms.inference}
