_target_: src.model.Conformer
input_dim: ${transforms.instance_transforms.train.get_spectrogram.n_mels}
model_dim: 144
num_attention_heads: 4
dim_head: 64
conv_kernel_size: 31
num_conformer_blocks: 16
input_dropout: 0.1
conv_dropout: 0.1
attention_dropout: 0.1
ffn_dropout: 0.1
ffn_expansion_factor: 4
conv_expansion_factor: 2
do_downsample: True
