defaults:
  - model: null
  - metrics: null 
  - device: null
  - datasets: librispeech
  - dataloader: basic
  - writer: null
  - transforms: null
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-2
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
# loss_function:
#   _target_: src.loss.CTCLossWrapper
trainer:
  n_epochs: 50
  epoch_len: 200
  skip_oom: null
  max_audio_length: 20.0
  max_text_length: 100
  dataset_partition: "test"
  device: auto
  base_sample_rate: 16000
