defaults:
  - model: conformer
  - writer: wandb
  - metrics: ArgMax_BeamSearch #change
  - datasets: inference_other
  - dataloader: local
  - transforms: basic
  - text_encoder: BpeEncoder #change
  - _self_
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example"
  seed: 1
  sample_rate: ${transforms.instance_transforms.train.get_spectrogram.sample_rate}
  from_pretrained: null
