defaults:
  - model: conformer
  - writer: wandb
  - metrics: ArgMax_BeamSearch
  - datasets: custom_dataset
  - dataloader: local
  - transforms: basic
  - text_encoder: BpeEncoder
  - _self_
partition_for_bpe:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example"
  seed: 1
  sample_rate: ${transforms.instance_transforms.train.get_spectrogram.sample_rate}
  show_augs: False
  from_pretrained: "saved/Run_kaggle/checkpoint-epoch17.pth"
  dataset_dir: null #path where the dataset contains 
