writer:
  _target_: src.logger.WandBWriter
  project_name: HW_ASR_FINAL
  entity: null
  run_name: testing
  mode: online
  loss_names:
  - loss
  log_checkpoints: false
  id_length: 8
  run_id: jhtfgn7b
datasets:
  train:
    _target_: src.datasets.LibrispeechDataset
    part: train-clean-360
    instance_transforms: ${transforms.instance_transforms.train}
  test:
    _target_: src.datasets.LibrispeechDataset
    part: test-clean
    instance_transforms: ${transforms.instance_transforms.inference}
transforms:
  instance_transforms:
    train:
      get_spectrogram:
        _target_: torchaudio.transforms.MelSpectrogram
        sample_rate: 16000
        hop_length: 160
        win_length: 400
        n_fft: 400
        n_mels: 80
    inference:
      get_spectrogram:
        _target_: torchaudio.transforms.MelSpectrogram
        sample_rate: 16000
        hop_length: 160
        win_length: 400
        n_fft: 400
        n_mels: 80
  batch_transforms:
    train: null
    inference: null
trainer:
  show_examples: 6
  sample_rate: ${transforms.instance_transforms.train.get_spectrogram.sample_rate}
  save_dir: save
