train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    hop_length: 160
    win_length: 400
    n_fft: 400
    n_mels: 80
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    hop_length: 160
    win_length: 400
    n_fft: 400
    n_mels: 80
